name: Verify Jupyter Notebook

on:
  push:
    branches:
      - dataset/preparation
  pull_request:
    branches:
      - main  # Replace with your branch name

jobs:
  test-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install notebook nbconvert

    - name: Execute Jupyter notebook
      run: |
        jupyter nbconvert --to notebook --execute --inplace path/to/your-notebook.ipynb
